config/routes.rb
Rails.application.routes.draw do
  # Mounting ActionCable sockets
    # Rails 6 does this by default
    # mount ActionCable.server => '/cable'

  # For all devise user controllers in user folder
  devise_for :users, :paths => 'users'

  # devise_for :users, controllers: {
  #   sessions: 'users/sessions',
  #   registration: 'users/registrations',
  # }
  
  resources :users do
    resources :chats, only: [:index, :show, :create] do 
      resources :messages
    end
  end


  root 'chats#index'
end

app/models/chat.rb
class Chat < ApplicationRecord
  # Destroys all messages and subscription if chat is destroyed
  # has_secure_token :identifier
  has_many :messages, dependent: :destroy
  has_many :subscriptions
  # Consider dependent: :destroy for subscriptions

  has_many :users, through: :subscriptions

  validates :identifier, presence: true, uniqueness: { case_sensitive: false }
end

app/controllers/chats_controller.rb
require 'securerandom'

class ChatsController < ApplicationController

  before_action :authenticate_user!

  def index
    @chats = current_user.chats
    @existing_chats_users = current_user.existing_chats_users
  end

  # Joining the chat
  def create
    @other_user = User.find(params[:other_user])
    # has_secure_token in chat.rb model generates a unique aplhanumeric token
    @chat = find_chat(@other_user) || Chat.new(identifier: SecureRandom.hex)
    # Creates a new subsscription for current and the other user with a single chat
    if !@chat.persisted?
      @chat.save
      @chat.subscriptions.create(user_id: current_user.id)
      @chat.subscriptions.create(user_id: @other_user.id)
    end
      
    redirect_to user_chat_path(
      current_user,
      @chat,
      :other_user => @other_user.id
    )
  end

  def show
    @other_user = User.find(params[:other_user])
    @chat = Chat.find(params[:id])
    @message = Message.new
    @messages = @chat.messages.order(created_at: :desc).limit(100).reverse
    @existing_chats_users = current_user.existing_chats_users
  end

  private
  def find_chat(second_user)  
    chats = current_user.chats
    
    chats.each do |chat|
      chat.subscriptions.each do |s|
        if s.user_id == second_user.id
          return chat
        end
      end
    end
    # If current user is not found, returns nil
    return nil
  end
end

app/helpers/chats_helper.rb
module ChatsHelper
end

app/views/chats/_sidebar.slim
#sidebar
  h4 All Users
  .user-list
    - User.all.each do | other_user |
      - if other_user != current_user
          = link_to( user_chats_path( current_user, :other_user => other_user.id ), method: :post ) do
            = other_user.username

app/views/chats/_sidenav.slim
#sidenav
  h4 Your Chats
  .user-list
    -if @existing_chats_users
      -@existing_chats_users.each do | other_user |
        -if other_user != current_user
          = link_to( user_chats_path( current_user, :other_user => other_user.id), method: :post ) do
            = other_user.username
  .content-bottom
    = link_to "#{current_user.username}", edit_user_registration_path, class: "block-links"
    = link_to "Logout", destroy_user_session_path, method: :delete, class: "block-links"

app/views/chats/index.html.slim
== render 'sidenav'

main
  h4 Chat
  .welcome-greet
    p Start a conversation

== render 'sidebar'



/ .fluid-container 
/   .row
/     .col-sm-2
/       == render 'sidenav'
/     .col-sm-10
/       main
/         .row
/           .col-sm-9
/             h4 Chat
/             .welcome-greet
/               p Start a conversation
/           .col-sm-3
/             == render 'sidebar'

app/views/chats/show.html.slim
== render 'sidenav'

/ .main{'data-behavior': 'messages'}
<main>
  = link_to "Back to chat list", user_chats_path(current_user.id)

  p Conversation with user
  h4 = @other_user.username

  <div data-behavior='messages'>
  
    -if @chat.messages.any?
      #messages
        == render partial: 'messages/message', collection: @messages
        / == render 'messages/message'
    -else
      #new-messages
        p No Current Message. Start a conversation!
      / == render partial: 'messages/message_form', locals: { message: @message, chat: @chat }
      / = form_for @message, remote: true do |form|
      /   = form.text_area :content, data: { textarea: "message" }, id: "new-message-textarea",
      /   onkeypress: "process(event, this)" ,placeholder: "Enter to send", class: "form-control"
      /   = form.hidden_field :chat_id, value: @chat.id
      /   = form.submit "Send"
    .message-form-bottom
      = form_for [@current_user, @chat, Message.new] do |f|
        = f.text_area :content, rows: 1, class: "form-control", autofocus: true
  </div>
</main>
== render 'sidebar'